name = "WFDB"
uuid = "803f460a-5458-4a91-aa64-df7c1af16fea"
authors = ["Brian Chen and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
